### ISSUE TITLE
Geckoview

### ISSUE THREAD

**Issue by eboye** [androidacy/WebviewSwitcher#2]
Is it possible to have webview switched to gecko (Firefox) and not chromium based browser?

**Comment by androidacy-user** [comment]
Unfortunately, Mozilla doesn't publish separate builds of just geckoview outside of Firefox builds.

**Comment by eboye** [comment]
Hmm, are you sure?

https://mozilla.github.io/geckoview/

https://searchfox.org/mozilla-central/source/mobile/android/geckoview

or do you mean the apk version?

**Comment by androidacy-user** [comment]
I reiterate: Mozilla doesn't publish _standalone_ builds of geckoview. It's meant to be bundled in an app.
